//------------------------------------------------------------------------------
// <auto-generated>
//     O código foi gerado por uma ferramenta.
//     Versão de Tempo de Execução:4.0.30319.1
//
//     As alterações ao arquivo poderão causar comportamento incorreto e serão perdidas se
//     o código for gerado novamente.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Resources.Properties {
    using System;
    
    
    /// <summary>
    ///   Uma classe de recurso de tipo de alta segurança, para pesquisar cadeias de caracteres localizadas etc.
    /// </summary>
    // Essa classe foi gerada automaticamente pela classe StronglyTypedResourceBuilder
    // através de uma ferramenta como ResGen ou Visual Studio.
    // Para adicionar ou remover um associado, edite o arquivo .ResX e execute ResGen novamente
    // com a opção /str, ou recrie o projeto do VS.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Retorna a instância de ResourceManager armazenada em cache usada por essa classe.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Resources.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Substitui a propriedade CurrentUICulture do thread atual para todas as
        ///   pesquisas de recursos que usam essa classe de recurso de tipo de alta segurança.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        public static System.Drawing.Bitmap basket {
            get {
                object obj = ResourceManager.GetObject("basket", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        public static System.Drawing.Bitmap button_cancelar {
            get {
                object obj = ResourceManager.GetObject("button_cancelar", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        public static System.Drawing.Bitmap button_editar {
            get {
                object obj = ResourceManager.GetObject("button_editar", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        public static System.Drawing.Bitmap button_excluir {
            get {
                object obj = ResourceManager.GetObject("button_excluir", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        public static System.Drawing.Bitmap button_imprimir {
            get {
                object obj = ResourceManager.GetObject("button_imprimir", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        public static System.Drawing.Bitmap button_janela {
            get {
                object obj = ResourceManager.GetObject("button_janela", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        public static System.Drawing.Bitmap button_limpar {
            get {
                object obj = ResourceManager.GetObject("button_limpar", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        public static System.Drawing.Bitmap button_novo {
            get {
                object obj = ResourceManager.GetObject("button_novo", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        public static System.Drawing.Bitmap button_salvar {
            get {
                object obj = ResourceManager.GetObject("button_salvar", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        public static System.Drawing.Bitmap delete {
            get {
                object obj = ResourceManager.GetObject("delete", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        public static System.Drawing.Bitmap dialog_error {
            get {
                object obj = ResourceManager.GetObject("dialog_error", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        public static System.Drawing.Bitmap dialog_important {
            get {
                object obj = ResourceManager.GetObject("dialog_important", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        public static System.Drawing.Bitmap dialog_information {
            get {
                object obj = ResourceManager.GetObject("dialog_information", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        public static System.Drawing.Bitmap dialog_stop {
            get {
                object obj = ResourceManager.GetObject("dialog_stop", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        public static System.Drawing.Bitmap dialog_urgent {
            get {
                object obj = ResourceManager.GetObject("dialog_urgent", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        public static System.Drawing.Bitmap dialog_warning {
            get {
                object obj = ResourceManager.GetObject("dialog_warning", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        public static System.Drawing.Bitmap logo_centercar {
            get {
                object obj = ResourceManager.GetObject("logo_centercar", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        public static System.Drawing.Bitmap logo_easysystem {
            get {
                object obj = ResourceManager.GetObject("logo_easysystem", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        public static System.Drawing.Bitmap logo_idea1 {
            get {
                object obj = ResourceManager.GetObject("logo_idea1", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        public static System.Drawing.Bitmap logo_idea1BIG {
            get {
                object obj = ResourceManager.GetObject("logo_idea1BIG", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        public static System.Drawing.Bitmap logo_idea2 {
            get {
                object obj = ResourceManager.GetObject("logo_idea2", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        public static System.Drawing.Bitmap logo_idea2BIG {
            get {
                object obj = ResourceManager.GetObject("logo_idea2BIG", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        public static System.Drawing.Bitmap logo_idea3BIG {
            get {
                object obj = ResourceManager.GetObject("logo_idea3BIG", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        public static System.Drawing.Bitmap logo_ideia4 {
            get {
                object obj = ResourceManager.GetObject("logo_ideia4", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        public static System.Drawing.Bitmap logo_legal {
            get {
                object obj = ResourceManager.GetObject("logo_legal", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        public static System.Drawing.Bitmap printer {
            get {
                object obj = ResourceManager.GetObject("printer", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        public static System.Drawing.Icon vnpo_cliente_pessoa_fisica {
            get {
                object obj = ResourceManager.GetObject("vnpo_cliente_pessoa_fisica", resourceCulture);
                return ((System.Drawing.Icon)(obj));
            }
        }
        
        public static System.Drawing.Icon vnpo_cliente_pessoa_juridica {
            get {
                object obj = ResourceManager.GetObject("vnpo_cliente_pessoa_juridica", resourceCulture);
                return ((System.Drawing.Icon)(obj));
            }
        }
        
        public static System.Drawing.Icon vnpo_condicional {
            get {
                object obj = ResourceManager.GetObject("vnpo_condicional", resourceCulture);
                return ((System.Drawing.Icon)(obj));
            }
        }
        
        public static System.Drawing.Icon vnpo_forma_pagamento_aprazo {
            get {
                object obj = ResourceManager.GetObject("vnpo_forma_pagamento_aprazo", resourceCulture);
                return ((System.Drawing.Icon)(obj));
            }
        }
        
        public static System.Drawing.Bitmap vnpo_forma_pagamento_avista {
            get {
                object obj = ResourceManager.GetObject("vnpo_forma_pagamento_avista", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        public static System.Drawing.Icon vnpo_forma_pagamento_cartao {
            get {
                object obj = ResourceManager.GetObject("vnpo_forma_pagamento_cartao", resourceCulture);
                return ((System.Drawing.Icon)(obj));
            }
        }
        
        public static System.Drawing.Icon vnpo_mudar_senha {
            get {
                object obj = ResourceManager.GetObject("vnpo_mudar_senha", resourceCulture);
                return ((System.Drawing.Icon)(obj));
            }
        }
        
        public static System.Drawing.Icon vnpo_relatorios {
            get {
                object obj = ResourceManager.GetObject("vnpo_relatorios", resourceCulture);
                return ((System.Drawing.Icon)(obj));
            }
        }
        
        public static System.Drawing.Icon vnpo_seguranca {
            get {
                object obj = ResourceManager.GetObject("vnpo_seguranca", resourceCulture);
                return ((System.Drawing.Icon)(obj));
            }
        }
        
        public static System.Drawing.Icon vnpo_servico_centercar {
            get {
                object obj = ResourceManager.GetObject("vnpo_servico_centercar", resourceCulture);
                return ((System.Drawing.Icon)(obj));
            }
        }
        
        public static System.Drawing.Bitmap vnpo_servico_ideia {
            get {
                object obj = ResourceManager.GetObject("vnpo_servico_ideia", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        public static System.Drawing.Icon vnpo_servico_quitar {
            get {
                object obj = ResourceManager.GetObject("vnpo_servico_quitar", resourceCulture);
                return ((System.Drawing.Icon)(obj));
            }
        }
        
        public static System.Drawing.Icon vnpo_venda {
            get {
                object obj = ResourceManager.GetObject("vnpo_venda", resourceCulture);
                return ((System.Drawing.Icon)(obj));
            }
        }
        
        public static System.Drawing.Icon vnpo_venda_quitar {
            get {
                object obj = ResourceManager.GetObject("vnpo_venda_quitar", resourceCulture);
                return ((System.Drawing.Icon)(obj));
            }
        }
        
        public static System.Drawing.Icon vnpo_virtual_numpad_options {
            get {
                object obj = ResourceManager.GetObject("vnpo_virtual_numpad_options", resourceCulture);
                return ((System.Drawing.Icon)(obj));
            }
        }
        
        public static System.Drawing.Icon vnpo_virtual_numpad_options_edit {
            get {
                object obj = ResourceManager.GetObject("vnpo_virtual_numpad_options_edit", resourceCulture);
                return ((System.Drawing.Icon)(obj));
            }
        }
        
        public static System.Drawing.Bitmap window_1Top1Left {
            get {
                object obj = ResourceManager.GetObject("window_1Top1Left", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        public static System.Drawing.Bitmap window_1Top2Center {
            get {
                object obj = ResourceManager.GetObject("window_1Top2Center", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        public static System.Drawing.Bitmap window_1Top3Right {
            get {
                object obj = ResourceManager.GetObject("window_1Top3Right", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        public static System.Drawing.Bitmap window_2Middle1Left {
            get {
                object obj = ResourceManager.GetObject("window_2Middle1Left", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        public static System.Drawing.Bitmap window_2Middle2Center {
            get {
                object obj = ResourceManager.GetObject("window_2Middle2Center", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        public static System.Drawing.Bitmap window_2Middle3Right {
            get {
                object obj = ResourceManager.GetObject("window_2Middle3Right", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        public static System.Drawing.Bitmap window_3Middle1Left {
            get {
                object obj = ResourceManager.GetObject("window_3Middle1Left", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        public static System.Drawing.Bitmap window_3Middle3Right {
            get {
                object obj = ResourceManager.GetObject("window_3Middle3Right", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        public static System.Drawing.Bitmap window_4Bottom1Left {
            get {
                object obj = ResourceManager.GetObject("window_4Bottom1Left", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        public static System.Drawing.Bitmap window_4Bottom2Center {
            get {
                object obj = ResourceManager.GetObject("window_4Bottom2Center", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        public static System.Drawing.Bitmap window_4Bottom3Right {
            get {
                object obj = ResourceManager.GetObject("window_4Bottom3Right", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        public static System.Drawing.Bitmap window_close1 {
            get {
                object obj = ResourceManager.GetObject("window_close1", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        public static System.Drawing.Bitmap window_close2 {
            get {
                object obj = ResourceManager.GetObject("window_close2", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        public static System.Drawing.Bitmap window_close3 {
            get {
                object obj = ResourceManager.GetObject("window_close3", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        public static System.Drawing.Bitmap window_maximize1 {
            get {
                object obj = ResourceManager.GetObject("window_maximize1", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        public static System.Drawing.Bitmap window_maximize2 {
            get {
                object obj = ResourceManager.GetObject("window_maximize2", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        public static System.Drawing.Bitmap window_maximize3 {
            get {
                object obj = ResourceManager.GetObject("window_maximize3", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        public static System.Drawing.Bitmap window_minimize1 {
            get {
                object obj = ResourceManager.GetObject("window_minimize1", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        public static System.Drawing.Bitmap window_minimize2 {
            get {
                object obj = ResourceManager.GetObject("window_minimize2", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        public static System.Drawing.Bitmap window_minimize3 {
            get {
                object obj = ResourceManager.GetObject("window_minimize3", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        public static System.Drawing.Bitmap window_restore1 {
            get {
                object obj = ResourceManager.GetObject("window_restore1", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        public static System.Drawing.Bitmap window_restore2 {
            get {
                object obj = ResourceManager.GetObject("window_restore2", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        public static System.Drawing.Bitmap window_restore3 {
            get {
                object obj = ResourceManager.GetObject("window_restore3", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
    }
}
